import os
from pathlib import Path
from datetime import datetime

# ==========================================
# Configuration & Paths
# ==========================================
BASE_DIR = Path(__file__).resolve().parent.parent
PUBLIC_DIR = BASE_DIR / "public"
VOICES_DIR = PUBLIC_DIR / "voices"

# ここにリポジトリのURLを設定してください
server_url = os.environ.get("GITHUB_SERVER_URL", None)
repo_path = os.environ.get("GITHUB_REPOSITORY", None)
REPO_URL = f"{server_url}/{repo_path}"

# ==========================================
# HTML Templates
# ==========================================
def render_page(title: str, content: str, show_back: bool = True) -> str:
    """共通のHTMLテンプレートを適用する"""
    back_link = f'<a href="index.html" class="back-link">← 戻る</a>' if show_back else ""
    
    return f"""<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | Voices Archive</title>
    <style>
        :root {{ --primary: #007bff; --bg: #f9f9f9; --text: #333; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; 
                line-height: 1.6; max-width: 800px; margin: 0 auto; background: var(--bg); color: var(--text); padding: 0 1rem; }}
        
        /* Header */
        header {{ display: flex; justify-content: space-between; align-items: center; padding: 2rem 0 1rem; border-bottom: 3px solid var(--primary); margin-bottom: 2rem; }}
        header h1 {{ margin: 0; font-size: 1.5rem; }}
        .github-link {{ text-decoration: none; color: var(--text); font-size: 0.9rem; display: flex; align-items: center; gap: 5px; }}
        .github-link:hover {{ opacity: 0.7; }}

        /* Content */
        .card {{ background: white; border: 1px solid #ddd; border-radius: 8px; padding: 1.2rem; margin-bottom: 1rem; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }}
        .filename {{ font-weight: bold; font-size: 0.85rem; color: #666; display: block; margin-bottom: 0.5rem; }}
        audio {{ width: 100%; }}

        /* Menu */
        .menu-item {{ display: flex; justify-content: space-between; align-items: center; 
                      padding: 1.2rem; background: white; margin: 0.8rem 0; text-decoration: none; 
                      color: var(--text); border-radius: 8px; border: 1px solid #ddd; transition: all 0.2s; }}
        .menu-item:hover {{ transform: translateY(-2px); border-color: var(--primary); box-shadow: 0 4px 12px rgba(0,0,0,0.1); }}
        .count {{ background: var(--primary); color: white; padding: 0.2rem 0.6rem; border-radius: 20px; font-size: 0.8rem; }}

        /* Footer & Navigation */
        footer {{ margin-top: 4rem; padding: 2rem 0; border-top: 1px solid #ddd; text-align: center; font-size: 0.8rem; color: #888; }}
        .back-link {{ display: inline-block; margin-top: 1rem; text-decoration: none; color: var(--primary); font-weight: bold; }}
    </style>
</head>
<body>
    <header>
        <h1>{title}</h1>
        <a href="{REPO_URL}" class="github-link" target="_blank" rel="noopener noreferrer">
            <svg height="20" width="20" viewBox="0 0 16 16"><path fill="currentColor" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path></svg>
            GitHub
        </a>
    </header>

    <main>
        {content}
        {back_link}
    </main>

    <footer>
        <p>&copy; {datetime.now().year} Voices Archive | Generated by Gemini & OpenAI</p>
        <p><a href="{REPO_URL}" style="color: inherit;">Source Code</a></p>
    </footer>
</body>
</html>
"""

# ==========================================
# Logic Functions
# ==========================================
def collect_voices() -> list[Path]:
    """voicesディレクトリ内のmp3ファイルを降順で取得"""
    return sorted(VOICES_DIR.glob("*.mp3"), reverse=True)

def group_by_month(files: list[Path]) -> dict[str, list[Path]]:
    """ファイルを年月(YYYYMM)ごとに辞書へ分類"""
    grouped = {}
    for f in files:
        ym = f.stem[:6]  # 先頭6文字を年月とする
        grouped.setdefault(ym, []).append(f)
    return grouped

def save_month_page(ym: str, files: list[Path]) -> str:
    """月別の個別ページを生成・保存し、目次用のリンクを返す"""
    dt = datetime.strptime(ym, "%Y%m")
    title = f"{dt.year}年{dt.month}月"
    file_name = f"{ym}.html"
    
    # リスト生成
    items = []
    for f in files:
        items.append(f"""
        <div class="card">
            <span class="filename">{f.name}</span>
            <audio controls src="voices/{f.name}" preload="none"></audio>
        </div>""")
    
    html_content = render_page(title, "\n".join(items))
    (PUBLIC_DIR / file_name).write_text(html_content, encoding="utf-8")
    
    return f'<a href="{file_name}" class="menu-item"><span>{title}</span> <span class="count">{len(files)}件</span></a>'

def save_index_page(links: list[str]):
    """メインの目次ページを生成・保存"""
    content = "\n".join(links)
    html_content = render_page("Voices Archive", content, show_back=False)
    (PUBLIC_DIR / "index.html").write_text(html_content, encoding="utf-8")

# ==========================================
# Main Orchestration
# ==========================================
def main():
    # 1. データの収集と整理
    voice_files = collect_voices()
    grouped_data = group_by_month(voice_files)
    
    # 2. 各月ページの生成
    index_links = []
    for ym, files in grouped_data.items():
        link_html = save_month_page(ym, files)
        index_links.append(link_html)
    
    # 3. 目次ペーの生成
    save_index_page(index_links)
    
    print(f"Success: Processed {len(voice_files)} files across {len(grouped_data)} months.")

if __name__ == "__main__":
    main()
